version: "3"
services:
  prisma-test:
    container_name: prisma-test
    platform: linux/amd64
    image: mysql
    restart: always
    ports:
      - "5455:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - prisma-test-volume:/var/lib/mysql

volumes:
  prisma-test-volume:
